name: Automated testing for pull request
on: [push]
env:
  PROJECT_ID: anan-project
  BUCKET_NAME: anan-gh-actions
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    env:
      SERVICE_NAME: blog/front
      PROJECT_ID: anan-project
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: projects/474794270878/locations/global/workloadIdentityPools/gh-pools/providers/gh-provider
          service_account: github-actions@anan-project.iam.gserviceaccount.com

      # Build docker image
      - name: Set Env
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Image
        run: |-
          docker build -t asia-northeast1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME:$tag .
      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker -q
      # Push image to Google Container Registry
      - name: Build
        run: |-
          docker push asia-northeast1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME:$tag
